Ozc/ju5 exper coaching
archis-academy/june-frontend-eskool-2 pull request #4
Opened 2024-07-11 14:31 UTC by ozcsert

![awdasdawdadad](https://github.com/archis-academy/june-frontend-eskool-2/assets/128157062/c818f91e-029d-4b27-acbb-50b50e85bec7)
section done.

2024-07-11 19:02 UTC, MehmetSunguralp commented on styles/style.css
> +.section-head__title {
font kalınlığı çok yüksek, tasarımdakini dikkate alalım

2024-07-11 19:03 UTC, MehmetSunguralp commented on styles/style.css
> +.cta-text {
font weight düşük kalmış, tasarımdakine uygun yapalım

2024-07-11 19:04 UTC, MehmetSunguralp requested changes
Sadece belirttiğim yerlerdeki font-weight değerlerini güncellersen master'a merge edebiliriz. Eline sağlık

2024-07-11 20:34 UTC, ozcsert commented
![aw opdkaskmasf](https://github.com/archis-academy/june-frontend-eskool-2/assets/128157062/3f0f3337-fb41-4bd9-88bc-40fa6e3886a9)
 font-weights ve cta border guncellendi.

2024-07-12 13:49 UTC, ozcsert commented
conflicts resolved

2024-07-13 15:06 UTC, MehmetSunguralp approved these changes

2024-07-13 15:07 UTC, merged