JU-6 New Course Bolumunu Tamamladım
archis-academy/june-frontend-eskool-2 pull request #5
Opened 2024-07-11 15:05 UTC by neslyhan

![image](https://github.com/archis-academy/june-frontend-eskool-2/assets/171554120/3b5fa033-55f6-4d9a-87a3-7fd3a15d0a46)

2024-07-13 15:09 UTC, MehmetSunguralp commented on images/new-course/under-part-tex1.png
Bu sayıları text olarak ekleyelim

2024-07-13 15:10 UTC, MehmetSunguralp commented on styles/style.css
> +  /* 32px */
Yorum satırlarını silebilirsin

2024-07-13 15:18 UTC, MehmetSunguralp requested changes
Yorumlardaki değişiklikleri güncelleyelim

2024-07-17 22:43 UTC, neslyhan commented on styles/style.css
> +  /* 32px */
Bu kısım (yorum satırları) Özcan'a ait HERO SECTION kısmı.

2024-07-19 12:51 UTC, merged