Ozc/ju9 high performance footer
archis-academy/june-frontend-eskool-2 pull request #8
Opened 2024-07-17 07:08 UTC by ozcsert

"sf pro display" font'unu @fontface ile eklemek zorundaydim cunku google-fonts da bulunmuyor. apple'da da linkini bulamadim.
![oahoaihdawodawd](https://github.com/user-attachments/assets/56e9a618-e617-4d94-8c1c-b63cc0e2cfb3)
section done.

2024-07-17 19:40 UTC, MehmetSunguralp requested changes
![image](https://github.com/user-attachments/assets/b99d90db-38cd-46cf-a3c7-687d434cb77c)
Şu taşmayı da önler misin?

2024-07-17 19:40 UTC, MehmetSunguralp commented on styles/style.css
> +}
Burada resime değil, resmin div'ine stil veriyorsun. Direkt img etiketine etkileyecek şekilde css'i düzenler misin?

2024-07-17 20:44 UTC, ozcsert commented
.img sınıfı düzenlendi. taşma problemi çözüldü.

2024-07-18 12:43 UTC, MehmetSunguralp commented
Conflict çözüldükten sonra merge edebilirim

2024-07-18 12:48 UTC, ozcsert commented
> Conflict çözüldükten sonra merge edebilirim
çözüldü

2024-07-18 12:48 UTC, merged